In [2]:
import tensorflow as tf
# X = tf.range(10)
# dataset = tf.data.Dataset.from_tensor_slices(X)
# dataset

In [4]:
dataset = tf.data.Dataset.range(10).repeat(3)
dataset = dataset.shuffle(buffer_size=5, seed=3).batch(7)
for item in dataset: print(item)

tf.Tensor([4 1 0 2 7 8 0], shape=(7,), dtype=int64)
tf.Tensor([6 9 2 5 3 5 3], shape=(7,), dtype=int64)
tf.Tensor([7 6 4 1 1 0 8], shape=(7,), dtype=int64)
tf.Tensor([4 9 2 7 9 5 3], shape=(7,), dtype=int64)
tf.Tensor([6 8], shape=(2,), dtype=int64)


In [6]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
scaler.fit(X_train)
X_mean = scaler.mean_
X_std = scaler.scale_

In [ ]:
def csv_reader_dataset(filepaths, repeat=1, n_readers=5, n_read_threads=None, 
    shuffle_buffer_size=10000, n_parse_threads=5, batch_size=32):
    dataset = tf.data.Dataset.list_files(filepaths)
    dataset = dataset.interleave(lambda filepath: tf.data)
    return